# Generated by Django 5.2.3 on 2025-07-20 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macAddr', models.CharField(max_length=18)),
                ('deviceName', models.CharField(max_length=28)),
                ('location', models.CharField(max_length=30)),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HumidityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envMonitor.device')),
            ],
        ),
        migrations.CreateModel(
            name='PressureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envMonitor.device')),
            ],
        ),
        migrations.CreateModel(
            name='RfidAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('webhook', 'webhook'), ('custom', 'custom')], max_length=30)),
                ('data', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envMonitor.device')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('unit', models.CharField(choices=[('Celsius', 'Celsius'), ('Fahrenheit', 'Fahrenheit')], max_length=11)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envMonitor.device')),
            ],
        ),
    ]
