# Generated by Django 5.2.3 on 2025-07-21 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envMonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 21, 1, 5, 27, 535857, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
