# Generated by Django 5.2.3 on 2025-07-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envMonitor', '0002_device_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
